apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecommerce-quota
  namespace: ecommerce
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ecommerce-limit-range
  namespace: ecommerce
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
