apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce-ui
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: ecommerce-ui
        image: rslim087/ecommerce-ui:latest
        imagePullPolicy: IFNotPresent
        ports:
        - containerPort: 4000
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: ecommerce-config
        - name: REACT_APP_SHIPPING_API_HOST
          value: "http://shipping-and-handling"
        - name: REACT_APP_CONTACT_API_HOST
          value: "http://contact-support-team"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  namespace: ecommerce
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: ecommerce-ui