apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-and-handling
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-and-handling
      version: v1
  template:
    metadata:
      labels:
        app: shipping-and-handling
        version: v1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: shipping-and-handling
        image: rslim087/shipping-and-handling:1.0.0
        imagePullPolicy: IFNotPresent
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: ecommerce-config
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-and-handling
  namespace: ecommerce
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: shipping-and-handling